events_path: cleaned_events.ev
cleaned_events_output_path: cleaned_events_finalised.ev

unparsed_transaction_addresses: unparsed_transaction_addresses.txt

payment_creds_mapping: payment_credentials.mapping
payment_creds_mapping_output: payment_credentials_finalised.mapping

staking_creds_mapping: staking_credentials.mapping
staking_creds_mapping_output: staking_credentials_finalised.mapping

banned_addresses: banned_addresses.txt
banned_addresses_output: banned_addresses_finalised.txt
